name: Publish new docs version

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TAG: ${{ github.ref_name }}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.TAG }}
      - name: Prepare the tag
        run: echo "TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Create a new version
        run: yarn docusaurus docs:version ${{ env.TAG }}
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add docs version v${{ env.TAG }}"
          git push origin HEAD:refs/heads/release-${{ env.TAG }}
          git pull origin release-${{ env.TAG }}
          echo -e "Update docs version v${{ env.TAG }}\\n\\nChangelog: https://github.com/rancher/turtles/releases/tag/v${{ env.TAG }}\\n\\ncc @rancher/highlander" > body
          export body=$(cat body)
          gh pr create -H release-${{ env.TAG }} --title 'turtles-docs release for turtles v${{ env.TAG }}' --body "$body"
