name: Publish new docs version

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TAG: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare the tag
        run: echo "TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Create a new version
        run: yarn docusaurus docs:version ${{ env.TAG }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: 'Add docs version ${{ env.TAG }}'
          body: |
            Add docs version ${{ env.TAG }}

            cc @rancher/highlander
          branch-suffix: short-commit-hash
          delete-branch: true